import Link from "next/link";
import { ProductBrand } from "./components/product-brand";
import { ThemeToggle } from "./components/theme-toggle";

export const metadata = { title: "SecureBin — private sharing, by design", description: "Browser-encrypted sharing for sensitive notes and files." };

function ArrowIcon() { return <svg viewBox="0 0 20 20" width="15" height="15" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true"><path d="M4 10h11m-5-5 5 5-5 5" /></svg>; }
function FeatureIcon({ type }: { type: "key" | "policy" | "code" | "file" | "discussion" | "parcel" }) {
  if (type === "key") return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true"><circle cx="8" cy="15" r="3.5" /><path d="m10.6 12.4 8-8m-2.1 2.1 2 2m-5-1 2 2" /></svg>;
  if (type === "policy") return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true"><path d="M5 7h9M5 12h6M5 17h9M17 14l2 2 3-4" /></svg>;
  if (type === "code") return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true"><path d="m8 8-4 4 4 4m8-8 4 4-4 4m-3-9-2 10" /></svg>;
  if (type === "file") return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true"><path d="M6 3h8l4 4v14H6zM14 3v5h5M9 13h6m-6 4h6" /></svg>;
  if (type === "discussion") return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true"><path d="M5 6.5A3.5 3.5 0 0 1 8.5 3h7A3.5 3.5 0 0 1 19 6.5v4a3.5 3.5 0 0 1-3.5 3.5H11l-4.5 4v-4.4A3.5 3.5 0 0 1 5 10.5zM9 8h6m-6 3h3" /></svg>;
  return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true"><path d="M4 7.5 12 3l8 4.5v9L12 21l-8-4.5zM4 7.5l8 4.5 8-4.5M12 12v9" /></svg>;
}
function Check() { return <span className="landing-check" aria-hidden="true">✓</span>; }

export default function LandingPage() {
  return <div className="landing-shell">
    <a className="skip-link" href="#landing-main">Skip to content</a>
    <header className="landing-header">
      <div className="landing-identity"><ProductBrand className="landing-brand" nameClassName="landing-brand-name" /><span className="landing-tagline">PRIVATE BY DESIGN</span></div>
      <nav className="landing-nav" aria-label="Primary navigation"><Link className="landing-nav-link landing-nav-link-active" href="#features">Features</Link><Link className="landing-nav-link" href="#security">Security</Link><a className="landing-nav-link" href="https://github.com/adithyarao2605/SecureBin/blob/main/self_hosting.md" target="_blank" rel="noreferrer">Self-Host</a><Link className="landing-nav-link" href="/new#how-it-works">Docs</Link></nav>
      <ThemeToggle />
    </header>
    <main id="landing-main">
      <section className="landing-hero" aria-labelledby="landing-title"><div className="landing-hero-copy"><h1 id="landing-title">Share sensitive<br />information.<br /><em>Stay in control.</em></h1><p className="landing-lede">Your browser encrypts notes and files before they leave the page. The server receives ciphertext, not plaintext.</p><div className="landing-actions"><Link className="landing-primary-action" href="/new">Create secure share <ArrowIcon /></Link><a className="landing-secondary-action" href="#security">How it works</a></div><div className="landing-proof-pills" aria-label="SecureBin properties"><span>♙ Client-side encryption</span><span>⌁ Password + unlock code</span><span>◷ Explicit release limits</span><span>📦 Offline parcels</span></div></div><div className="landing-composer-preview" aria-label="Preview of the SecureBin share composer"><div className="landing-preview-tabs"><span className="active">Plain note</span><span>Markdown</span><span>Code</span><span className="landing-preview-settings" aria-hidden="true">⚙</span></div><p className="landing-preview-placeholder">A share preview: write sensitive content, choose its policy, and seal it in the browser.</p><div className="landing-preview-footer"><span>◷ &nbsp;One reveal · expires in 24 hours</span><Link href="/new">Create share</Link></div></div></section>
      <section className="landing-section landing-why" id="features" aria-labelledby="why-title"><div className="landing-section-intro"><p className="landing-section-kicker">One product surface · several safe ways to share</p><h2 id="why-title">Everything important stays visible.</h2><p>SecureBin brings the protection policy, encrypted material, and honest limits into the same flow so a sender can understand what happens before sharing.</p></div><div className="landing-feature-grid" id="security"><article><FeatureIcon type="key" /><h3>Encryption stays local</h3><p>Notes, files, keys, passwords, and unlock codes are handled in your browser. The service receives ciphertext and bounded lifecycle metadata.</p></article><article><FeatureIcon type="policy" /><h3>Explicit release policy</h3><p>Choose availability, expiry, reveal limits, passwords, and a separate unlock code for each share.</p></article><article><FeatureIcon type="code" /><h3>Notes, Markdown, and code</h3><p>Write plain notes, render GitHub-Flavored Markdown, or use an editable syntax-highlighted code IDE.</p></article><article><FeatureIcon type="file" /><h3>Encrypted files</h3><p>Attach multiple files, preview safe formats, download individual files, or create a local encrypted ZIP.</p></article><article><FeatureIcon type="discussion" /><h3>Encrypted discussion</h3><p>Enable threaded replies after reveal, with encrypted bodies and browser-held edit and delete proofs.</p></article><article><FeatureIcon type="parcel" /><h3>Portable proof</h3><p>Inspect the Privacy Receipt, manage local share history, revoke future releases, or restore a .securebin parcel offline.</p></article></div></section>
      <section className="landing-section landing-capabilities" id="self-hosting" aria-labelledby="capabilities-title"><div><p className="landing-section-kicker">Visible capabilities</p><h2 id="capabilities-title">Built for real handoffs.</h2><div className="landing-capability-list"><span><Check />AES-256-GCM</span><span><Check />Reveal limits</span><span><Check />Password + unlock code</span><span><Check />Syntax highlighting</span><span><Check />Markdown rendering</span><span><Check />Encrypted attachments</span><span><Check />Privacy Receipt</span><span><Check />Offline parcels</span><span><Check />No plaintext logs</span><span><Check />Self-hostable</span></div></div><div><h2>Run it your way</h2><div className="landing-terminal" aria-label="Self-hosting command preview"><div className="landing-terminal-dots"><i /><i /><i /></div><code><span># Start the verified local stack</span><br /><b>pnpm local:setup</b><br /><b>pnpm local</b></code></div></div></section>
    </main>
    <footer className="landing-footer"><div><strong>SecureBin</strong><span>Zero-knowledge by design.</span></div><nav aria-label="Footer navigation"><a href="#features">Features</a><Link href="/new#how-it-works">Docs</Link><a href="https://github.com/adithyarao2605/SecureBin/blob/main/self_hosting.md" target="_blank" rel="noreferrer">Self-Hosting</a><a href="https://github.com/adithyarao2605/SecureBin" rel="noreferrer">GitHub</a></nav></footer>
  </div>;
}
